// import { APP_NAME } from "@/configs/env";
// import "../styles/globals.css";
// import { Metadata } from "next";

// export const metadata: Metadata = {
//     title: 'Next.js',
//     description: 'Generated by Next.js',
// }


// export default function Head(metadata: Metadata) {
//     return (
//         <Head></Head>
//     );
// }
